services:
  mariadb:
    container_name: mariadb
    networks:
      - backend
    env_file:
      - path: ./.env
        required: true
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PWD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    build:
      context: ./
      dockerfile: ./mariadb/Dockerfile
    volumes:
      - mariadb_data:/var/lib/mysql

  wordpress-php:
    container_name: wordpress-php
    depends_on:
      - mariadb
    networks:
      - frontend
      - backend
    env_file:
      - path: ./.env
        required: true
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${MARIADB_DATABASE}
      WORDPRESS_DB_USER: ${MARIADB_USER}
      WORDPRESS_DB_PASSWORD: ${MARIADB_PASSWORD}
    build:
      context: ./
      dockerfile: ./wordpress/Dockerfile
    volumes:
      - wordpress_files:/var/www/html

  nginx:
    container_name: nginx
    depends_on:
      - wordpress-php
    ports:
      - "443:443"
    networks:
      - frontend
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    volumes:
      - wordpress_files:/var/www/html:ro

volumes:
  wordpress_files:
    driver: local
  mariadb_data:
    driver: local

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge